# permissions for end users to view foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: foo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: foo-viewer-role
rules:
- apiGroups:
  - tutorial.jerry.org
  resources:
  - foos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tutorial.jerry.org
  resources:
  - foos/status
  verbs:
  - get
